### ISSUE TITLE
DirectX Effect files detected as Flux

### ISSUE THREAD

**Issue by kusma** [github/linguist#2841]
DirectX Effect files (*.fx) gets detected as Flux. See for example here:
https://github.com/kusma/vlee/search?l=flux

This seems rather common:
https://github.com/search?utf8=%E2%9C%93&q=extension%3Afx+NOT+nothack&type=Code&ref=searchresults

**Comment by pchaigno** [comment]
I'm sure DirectX Effect would be accepted as a new language if it meets the requirements. Please see the [contribution guidelines](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) on how to add a new language ;)

**Comment by kusma** [comment]
I gave adding HLSL/fx a go, [here](https://github.com/kusma/linguist/tree/hlsl)

However, it seems to make the test-suite a bit angry:
```
  1) Error:
TestBlob#test_language:
NoMethodError: undefined method `[]' for nil:NilClass
    /home/ubuntu/workspace/lib/linguist/classifier.rb:131:in `token_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:120:in `block in tokens_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `each'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `inject'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `tokens_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:105:in `block in classify'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:104:in `each'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:104:in `classify'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:78:in `classify'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:20:in `call'
    /home/ubuntu/workspace/lib/linguist/language.rb:116:in `block (3 levels) in detect'
    /home/ubuntu/workspace/lib/linguist.rb:17:in `instrument'
    /home/ubuntu/workspace/lib/linguist/language.rb:115:in `block (2 levels) in detect'
    /home/ubuntu/workspace/lib/linguist/language.rb:113:in `each'
    /home/ubuntu/workspace/lib/linguist/language.rb:113:in `block in detect'
    /home/ubuntu/workspace/lib/linguist.rb:17:in `instrument'
    /home/ubuntu/workspace/lib/linguist/language.rb:108:in `detect'
    /home/ubuntu/workspace/lib/linguist/blob_helper.rb:328:in `language'
    /home/ubuntu/workspace/test/test_file_blob.rb:601:in `block in test_language'
    /home/ubuntu/workspace/lib/linguist/samples.rb:60:in `block (2 levels) in each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:38:in `each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:38:in `block in each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:34:in `each'    /home/ubuntu/workspace/lib/linguist/samples.rb:34:in `each'
    /home/ubuntu/workspace/test/test_file_blob.rb:599:in `test_language'
  2) Error:
TestClassifier#test_classify_ambiguous_languages:
NoMethodError: undefined method `[]' for nil:NilClass
    /home/ubuntu/workspace/lib/linguist/classifier.rb:131:in `token_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:120:in `block in tokens_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `each'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `inject'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:119:in `tokens_probability'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:105:in `block in classify'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:104:in `each'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:104:in `classify'
    /home/ubuntu/workspace/lib/linguist/classifier.rb:78:in `classify'
    /home/ubuntu/workspace/test/test_classifier.rb:52:in `block in test_classify_ambiguous_languages'
    /home/ubuntu/workspace/lib/linguist/samples.rb:60:in `block (2 levels) in each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:38:in `each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:38:in `block in each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:34:in `each'
    /home/ubuntu/workspace/lib/linguist/samples.rb:34:in `each'
    /home/ubuntu/workspace/test/test_classifier.rb:47:in `test_classify_ambiguous_languages'

928 runs, 8823 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib" -I"/home/ubuntu/workspace/vendor/gems/ruby/2.3.0/gems/rake-10.5.0/lib" "/home/ubuntu/workspace/vendor/gems/ruby/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/test*.rb" ]
```

Any clue?

**Comment by arfon** [comment]
Did you run `bundle exec rake samples` first?

**Comment by kusma** [comment]
No I did not. Thanks for the tip!

**Comment by kusma** [comment]
That did indeed do the trick, thanks!

**Comment by arfon** [comment]
> That did indeed do the trick, thanks!

:+1:
