### ISSUE TITLE
PAWN/SourcePawn misclassified as Pascal

### ISSUE THREAD

**Issue by NexiusTailer** [github/linguist#3050]
PAWN/SourcePawn misclassified as Pascal (but a very small part, about 0.1%)
https://github.com/NexiusTailer/Nex-AC

**Comment by pchaigno** [comment]
Linguist detection fails on [this file](https://github.com/NexiusTailer/Nex-AC/blob/master/lang/nex-ac_pt_br.inc) because it's a UTF-16 encoded:
```
$ bundle exec linguist ../Nex-AC/lang/nex-ac_pt_br.inc 
/linguist/lib/linguist/blob_helper.rb:281:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /linguist/lib/linguist/blob_helper.rb:281:in `lines'
	from /linguist/lib/linguist/blob_helper.rb:298:in `loc'
	from /linguist/bin/linguist:49:in `<top (required)>'
	from /.rvm/gems/ruby-2.3.0/bin/linguist:23:in `load'
	from /.rvm/gems/ruby-2.3.0/bin/linguist:23:in `<main>'
	from /.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
This seems related to #353.

**Comment by pchaigno** [comment]
Closing in favor of #353.
