### ISSUE TITLE
bash: bundle: command not found

### ISSUE THREAD

**Issue by drandreaskrueger** [github/linguist#4495]
## Preliminary Steps

Please confirm you have...
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

    bundle exec bin/github-linguist --breakdown
    bash: bundle: command not found

### how to reproduce

```
sudo apt-get install cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
git clone https://github.com/github/linguist github_linguist
cd github_linguist/

gem install github-linguist
sudo gem install github-linguist

bundle exec bin/github-linguist --breakdown
```

On Debian:

> uname -a
> Linux ... 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux

**Comment by drandreaskrueger** [comment]
I guess this would fix it, because then I did not need sudo anymore:

```
mkdir ~/.ruby
echo 'export GEM_HOME=~/.ruby' >> ~/.bashrc
echo 'export PATH="$PATH:~/.ruby/bin"' >> ~/.bashrc
source ~/.bashrc

gem install bundler
gem install github-linguist
```

and then 
```
bundle install
bundle exec bin/github-linguist --breakdown
```

but now unfortunately, the `bundle install` results in this:

```
bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.10)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.10)' in any of the relevant sources:
  the local ruby installation
```

what to do?

Thanks

**Comment by drandreaskrueger** [comment]
P.S.: versions:

```
bundle --version; ruby --version; gem --version
Bundler version 2.0.1
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
2.5.2.1

git log | head -n 1
commit 7551e736ee126d29b4977983a41fe25d073c37cd
```

**Comment by pchaigno** [comment]
@lildude Doesn't Linguist work with more recent versions of bundler? Couldn't we update `github-linguist.gemspec`?

**Comment by drandreaskrueger** [comment]
tried to just patch that .gemspec, but then I get:

``` 
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 2.0)

    licensed (~> 1.3.0) was resolved to 1.3.4, which depends on
      bundler (~> 1.10)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

**Comment by drandreaskrueger** [comment]
another attempt

```
gem install bundler -v '=1.10' 
Successfully installed bundler-1.10.0
Parsing documentation for bundler-1.10.0
Done installing documentation for bundler after 2 seconds
1 gem installed
```
```
bundle _1.10.0_ install 
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.10)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.10)' in any of the relevant sources:
  the local ruby installation
```
not successful. 

but my ruby experience is very very limited.

**Comment by pchaigno** [comment]
Try:
```
gem uninstall bundler --version 2.0.1
```

**Comment by pchaigno** [comment]
> @lildude Doesn't Linguist work with more recent versions of bundler? Couldn't we update `github-linguist.gemspec`?

Looks like we should update the version of licensed as well...

**Comment by drandreaskrueger** [comment]
that worked:

```
sudo gem uninstall bundler --version 2.0.1
sudo gem uninstall bundler --version 1.10.0
gem uninstall bundler --version 1.10.0
gem uninstall bundler --version 2.0.1

gem install bundler -v '=1.10' 
bundle install
```
Thanks!!

but now I get this new problem:
```
bundle exec bin/github-linguist --breakdown
bundler: failed to load command: bin/github-linguist (bin/github-linguist)
LoadError: cannot load such file -- linguist/linguist
  /home/andreas/Documents/Code/github_linguist/lib/linguist/tokenizer.rb:2:in `require'
  /home/andreas/Documents/Code/github_linguist/lib/linguist/tokenizer.rb:2:in `<top (required)>'
  /home/andreas/Documents/Code/github_linguist/lib/linguist/classifier.rb:1:in `require'
  /home/andreas/Documents/Code/github_linguist/lib/linguist/classifier.rb:1:in `<top (required)>'
  /home/andreas/Documents/Code/github_linguist/lib/linguist/language.rb:8:in `require'
  /home/andreas/Documents/Code/github_linguist/lib/linguist/language.rb:8:in `<top (required)>'
  /home/andreas/Documents/Code/github_linguist/lib/linguist.rb:5:in `require'
  /home/andreas/Documents/Code/github_linguist/lib/linguist.rb:5:in `<top (required)>'
  bin/github-linguist:5:in `require'
  bin/github-linguist:5:in `<top (required)>'
```

**Comment by pchaigno** [comment]
What about `bundle exec github-linguist --breakdown`?

**Comment by drandreaskrueger** [comment]
thx

```
bundle exec github-linguist --breakdown

~/github_linguist/lib/linguist/tokenizer.rb:2:in `require': cannot load such file -- linguist/linguist (LoadError)
	from ~/github_linguist/lib/linguist/tokenizer.rb:2:in `<top (required)>'
	from ~/github_linguist/lib/linguist/classifier.rb:1:in `require'
	from ~/github_linguist/lib/linguist/classifier.rb:1:in `<top (required)>'
	from ~/github_linguist/lib/linguist/language.rb:8:in `require'
	from ~/github_linguist/lib/linguist/language.rb:8:in `<top (required)>'
	from ~/github_linguist/lib/linguist.rb:5:in `require'
	from ~/github_linguist/lib/linguist.rb:5:in `<top (required)>'
	from ~/github_linguist/bin/github-linguist:5:in `require'
	from ~/github_linguist/bin/github-linguist:5:in `<top (required)>'
	from ~/.ruby/bin/github-linguist:22:in `load'
	from ~/.ruby/bin/github-linguist:22:in `<main>'

bundle --version
Bundler version 1.17.3

```

**Comment by drandreaskrueger** [comment]
Hah.

this was a random find, but a good one:

```
~/.ruby/bin/github-linguist
67.73%  Ruby
22.64%  C
7.61%   Go
1.19%   Lex
0.56%   Shell
0.27%   Dockerfile
```

so, I got it working. And you should consider to update your README.md to account for this?

**Comment by lildude** [comment]
> You should perhaps consider to update your README.md to account for this?

We can't really document for all the different ruby envs peeps can use, but we certainly do already document the Bundler requirements in CONTRIBUTING.md - https://github.com/github/linguist/blob/master/CONTRIBUTING.md#dependencies - or am I missing something else?

> @lildude Doesn't Linguist work with more recent versions of bundler? Couldn't we update `github-linguist.gemspec`?

It most certainly does, but it's licensed that has the 1.x requirement - https://github.com/github/licensed/blob/afba288df344e001d43e94ad9217635a011b79c2/licensed.gemspec#L30

> Looks like we should update the version of licensed as well...

Yup, though we'd still be locked to Bundler 1.x 😄

**Comment by drandreaskrueger** [comment]
dunno, really. not much ruby experience. 

my problem is solved. if you want to, then:

CanClose.
