### ISSUE TITLE
Several classifier is throwing exceptions on GitHub.com staging

### ISSUE THREAD

**Issue by lildude** [github/linguist#4995]
This is a tracking issue for my own purposes.

Whilst testing a deployment of v7.11.0 on GitHub staging, I discovered the linguist classifier is throwing an exception. I saw this locally when testing and put this down to something wrong with my local env as our CI wasn't failing at all, but this clearly isn't specific to me.

The failures I am seeing when running the test locally are:

```
  1) Error:
TestBlob#test_language:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:133:in `token_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:122:in `block in tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `inject'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:107:in `block in classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:80:in `classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:22:in `call'
    /Users/lildude/github/linguist/lib/linguist.rb:32:in `block (3 levels) in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:100:in `instrument'
    /Users/lildude/github/linguist/lib/linguist.rb:31:in `block (2 levels) in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:29:in `each'
    /Users/lildude/github/linguist/lib/linguist.rb:29:in `block in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:100:in `instrument'
    /Users/lildude/github/linguist/lib/linguist.rb:24:in `detect'
    /Users/lildude/github/linguist/lib/linguist/blob_helper.rb:368:in `language'
    /Users/lildude/github/linguist/test/test_blob.rb:251:in `block in test_language'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:58:in `block (2 levels) in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `block in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/test/test_blob.rb:249:in `test_language'

  2) Error:
TestClassifier#test_classify_ambiguous_languages:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:133:in `token_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:122:in `block in tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `inject'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:107:in `block in classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:80:in `classify'
    /Users/lildude/github/linguist/test/test_classifier.rb:55:in `block in test_classify_ambiguous_languages'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:58:in `block (2 levels) in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `block in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/test/test_classifier.rb:47:in `test_classify_ambiguous_languages'

  3) Error:
TestFileBlob#test_language:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:133:in `token_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:122:in `block in tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `inject'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:121:in `tokens_probability'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:107:in `block in classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `each'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:106:in `classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:80:in `classify'
    /Users/lildude/github/linguist/lib/linguist/classifier.rb:22:in `call'
    /Users/lildude/github/linguist/lib/linguist.rb:32:in `block (3 levels) in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:100:in `instrument'
    /Users/lildude/github/linguist/lib/linguist.rb:31:in `block (2 levels) in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:29:in `each'
    /Users/lildude/github/linguist/lib/linguist.rb:29:in `block in detect'
    /Users/lildude/github/linguist/lib/linguist.rb:100:in `instrument'
    /Users/lildude/github/linguist/lib/linguist.rb:24:in `detect'
    /Users/lildude/github/linguist/lib/linguist/blob_helper.rb:368:in `language'
    /Users/lildude/github/linguist/test/test_file_blob.rb:646:in `block in test_language'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:58:in `block (2 levels) in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:41:in `block in each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/lib/linguist/samples.rb:37:in `each'
    /Users/lildude/github/linguist/test/test_file_blob.rb:644:in `test_language'
```

The exceptions on GitHub staging have the same backtrace.

I've reproduced these same errors after checking out v7.10.0 which I know passed all the tests locally for me so I don't believe this is due to something we changed.

**Comment by lildude** [comment]
🤦 well that's embarrassing. This _is_ due to my local env after all. The problem doesn't exist if I perform a fresh clone of the repo. I suspect something went awry with building the tokeniser in my original repo that has caused the problem. Back to normal service.

**Comment by smola** [comment]
@lildude I'm experiencing this when using linguist as a library:

```ruby
require 'linguist'
path = ARGV[0]
blob = Linguist::FileBlob.new(path)
candidates = Linguist::Strategy::Extension.call(blob, [])
Linguist::Classifier.call(blob, candidates)
```

Example file: https://github.com/smola/language-dataset/blob/master/data/github.com/AJMartel/IRTriage/edfc35dde062c32bd4e03deb821c88ed6fc65d83/Compile/Tools/Updater/My_Github_Updates_Calculator.au3

**Comment by lildude** [comment]
@smola This doesn't look like a new issue with Linguist and I believe such a failure has always existed.

Your example is failing because there isn't, and never has been, an `AutoIt` sample for the classifier to run against.

Under normal usage, we'd never get to the classifier in this instance as the extension strategy only returns a single entry so we'd never move on to the classifier thanks to:

https://github.com/github/linguist/blob/8083cb5a89cee2d99f5a988f165994d0243f0d1e/lib/linguist.rb#L34-L36

This will be why running `github-linguist My_Github_Updates_Calculator.au3` returns the correct language without throwing an exception.

**Comment by lildude** [comment]
Yup, I've just done a quick test with random versions of Linguist going back to 5.0.0 and your code always fails in exactly the same way because of the lack of an `AutoIt` sample.
