### ISSUE TITLE
 Could not gem install github-linguist on Mac OS Catalina

### ISSUE THREAD

**Issue by majac91** [github/linguist#5195]
## The issue
I tried to install linguist by executing ```gem install github-linguist``` which failed with ``` fatal error: 'ruby/config.h' file not found #include "ruby/config.h"```  in the error log.

<a href='https://github.com/majac91/Photography_portfolio_V2'>Project repo</a>
Ruby version: 2.6.3p62

```
maja@Majas-MacBook-Pro Photography_portfolio_V2 % gem install github-linguist
Fetching github-linguist-7.12.2.gem
Fetching escape_utils-1.2.1.gem
Fetching mini_mime-1.0.2.gem
Fetching rugged-1.1.0.gem
Fetching charlock_holmes-0.7.7.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
maja@Majas-MacBook-Pro Photography_portfolio_V2 % sudo gem install github-linguist
Password:
Fetching mini_mime-1.0.2.gem
Fetching github-linguist-7.12.2.gem
Fetching charlock_holmes-0.7.7.gem
Fetching escape_utils-1.2.1.gem
Fetching rugged-1.1.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing github-linguist:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210207-85253-95znya.rb extconf.rb
checking for -licui18n... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
        --with-icu-dir
        --without-icu-dir
        --with-icu-include
        --without-icu-include=${icu-dir}/include
        --with-icu-lib
        --without-icu-lib=${icu-dir}/lib
        --with-icu-i18n-config
        --without-icu-i18n-config
        --with-pkg-config
        --without-pkg-config
        --with-icu-io-config
        --without-icu-io-config
        --with-pkg-config
        --without-pkg-config
        --with-icu-uc-config
        --without-icu-uc-config
        --with-pkg-config
        --without-pkg-config
        --with-icui18nlib
        --without-icui18nlib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:39:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/charlock_holmes-0.7.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/charlock_holmes-0.7.7 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/charlock_holmes-0.7.7/gem_make.out
```

### Attempted solutions 
 
I ran ```brew install cmake pkg-config icu4c``` and tried installing again with no luck. 

From <a href='https://github.com/github/linguist/issues/4484#issuecomment-717471378'>this</a> issue I then ran

```sudo gem install charlock_holmes -- --with-icu-dir=/usr/local/opt/icu4c --with-cxxflags='-Wno-reserved-user-defined-literal -std=c++11' ``` which failed with the same error, as well as 

```sudo gem install github-linguist --version "7.12.2" --source "https://rubygems.pkg.github.com/github"```

I did notice the solutions that suggest  <a href='https://github.com/github/linguist/issues/4484#issuecomment-479612716'>modifying certain lines</a> but they are in the file I'm missing.

**Comment by lildude** [comment]
Unfortunately, this isn't a bug in Linguist, nor charlock-holmes (which is the gem that's struggling here) but rather a problem with the Ruby as shipped with macOS.

See my comments at https://github.com/github/linguist/pull/4918#issuecomment-679028679 and https://github.com/github/linguist/issues/5147#issuecomment-761051470

I'm in the process of updating the docs in which I'll be adding a note discouraging the use of the macOS Ruby because of this precise reason, and the fact that Apple has already announced they'll stop shipping Ruby so really have no incentive to fix this or any other issues.
